version: '3.7'  
services:
    
  app:
    build:
        context: .
        dockerfile: docker/Dockerfile
    # При изменении образа в Dockerfile
    # нужно изменить название и здесь
    # во избежание перезатирания образов
    image: 'symfony_lamp_php8.2'
    ports:
        - 8081:80
    volumes:
        - ./:/var/www/html

# Совет CLI при удалении контейнеров из этого файла и запуске команды
# docker-compose -up d 
# :
# If you removed or renamed this service in your compose file, 
# you can run this command with the --remove-orphans flag to clean it up
# То есть
# docker-compose -up d --remove-orphans