version: '3.7'  
services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports: 
        - "3308:3306"
    environment:
    # имя базы данных задаётся здесь
        MYSQL_DATABASE: 'symfony_db'
        # MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_ROOT_PASSWORD: "123"
        # Log in: db, root, 123
    # volumes:
    #    - ./dbfiles:/var/lib/mysql
    # не увидел смысла в наличии файлов mysql, лучше сделать dump.sql
    command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
  
  app:
    build:
        context: .
        dockerfile: docker/Dockerfile
    # При изменении образа в Dockerfile
    # нужно изменить название и здесь
    # во избежание перезатирания образов
    image: 'symfony_lamp_php8.2'
    ports:
        - 8081:80
    volumes:
        - ./:/var/www/html

  adminer:           # имя контейнера
    image: adminer
    restart: on-failure
    ports:           # порты - локальный:внутри_контейнера
      - 6081:8080
    environment:
      ADMINER_DESIGN: rmsoft_blue # синее оформление